#!/usr/bin/env python

import argparse
import json

import boto3

parser = argparse.ArgumentParser(description='Return the URL of your webapp')
parser.add_argument(
    'params',
    type=argparse.FileType('r'),
    help='JSON file with your servers template parameters',
    metavar='PARAMS'
)

args = parser.parse_args()
# Flatten the params
params = {
    p["ParameterKey"]: p["ParameterValue"]
    for p in json.load(args.params)
}

url_export_key_name = params["OutputUrlKeyName"]

client = boto3.client('cloudformation')
exports = client.list_exports()['Exports']
url = ''
for export in exports:
    if export['Name'] == url_export_key_name:
        url = export['Value']
        break

print(url)
