Description: >
  Deployment of the data store of the project (Udagram).

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names.
    Type: String

  S3BucketName:
    Description: The name of the S3 bucket where the ZipFileName is stored.
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      AccessControl: BucketOwnerFullControl
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
    DeletionPolicy: Delete

  # BucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     PolicyDocument:
  #       Id: MyPolicy
  #       Version: 2012-10-17
  #       Statement:
  #         - Sid: PublicReadForGetBucketObjects
  #           Effect: Allow
  #           Principal: '*'
  #           Action: 's3:GetObject'
  #           Resource: !Join
  #             - ''
  #             - - 'arn:aws:s3:::'
  #               - !Ref S3Bucket
  #               - /*
  #     Bucket: !Ref S3Bucket

Outputs:
  BucketName:
    Value: !Ref S3Bucket
    Description: The Bucket name for developers to use
    Export:
      Name: !Sub ${EnvironmentName}-BUCKET
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - S3Bucket
          - DomainName
    Description: HTTPs endpoint of the bucket
    Export:
      Name: !Sub ${EnvironmentName}-S3-URL
